name: Python application
defaults:
  run:
    shell: bash
    working-directory: ./delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
       pip install -e .['dev'] 
    - name: Set a dummy secret key
      run: echo "::set-env name=FLASK_SECRET_KEY::avocodes01"
         
    - name: Run tests
      run: |
       FLASK_ENV=test pytest tests/ -v --cov=delivery
