name: Python application
defaults:
  run:
    shell: bash
    working-directory: ./delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
       make install
    - name: Set a dummy secret key
      run: echo "::set-env name=FLASK_SECRET_KEY::avocodes01"

    - name: Database Migrations
      run: |
       make init_db
       
    - name: Run tests
      run: |
       make test
